name: Build & Test & Deploy PROD STAGING

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - staging
      - main
  push:
    branches:
      - staging
      - main
  schedule:
    - cron: '*/1 * * * *'  # Every one minute
  # To trigger manually
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: 'test'
        shell: bash
        run: |
          echo "test"
  build:
    name: Build & Deploy Staging Production
    needs: test
    # needs: ci.test-coverage
    runs-on: ubuntu-latest
    if:
      contains('
      refs/heads/staging
      refs/heads/main
      ', github.ref)
    steps:
      - name: 'build'
        shell: bash
        run: |
          echo "build"
